Update Jekyll and jekyll-github-metadata to newest available versions
AnnaDodson/hacktoberfest-website pull request #88
Opened 2020-10-01 18:42 UTC by bitshiftsdotio

This PR updates Jekyll and jekyll-github-metadata to the newest available versions. This removes the dependency on the now-deprecated `sass` gem (which has been replaced with `sassc`), thus closing #51.

It also has side-effects for #49.

2020-10-02 20:07 UTC, jamietanna requested changes

2020-10-02 20:07 UTC, jamietanna commented on Gemfile.lock
> +   2.1.4
It looks like this change may have been the issue? Mind trying to revert it? ☺

2020-10-02 21:06 UTC, bitshiftsdotio commented
@jamietanna the build seems to have succeeded now!

2020-10-03 13:45 UTC, AnnaDodson approved these changes

2020-10-03 13:45 UTC, merged